openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
          # Missing content definition
    post:
      summary: Create a new user
      # Missing requestBody
      responses:
        '201':
          description: User created
